Pattern acceleration refactor
teragrep/pth_06 pull request #85
Opened 2024-09-09 07:46 UTC by elliVM

Pattern acceleration feature to activate bloom filtering on set regex pattern. Goal is to limit bloom filtering to certain patterns like UUID.

Flow:
1. Walker walks XML and for each search term regex checks tokenized term against tables in bloomdb excluding the filtertype table
2. Collect list of tables with a pattern match record from SQL metadata
3. For each table a temp table is created
4. For each temp table generate condition that compares temp table filter against parent table filter using bloommatch UDF
5. Combine conditions from each table, if all filters were null then also true
7. Left join tables to NestedTopNQuery and use the combined condition

Notes: Tokenizer max token count is set to 0 to get only major tokens since that is what dpf_03 currently uses to tokenize the bloom filter tables

2024-09-09 11:13 UTC, eemhu commented on src/main/java/com/teragrep/pth_06/planner/BloomFilterTempTable.java
> +        this.parentTable = parentTable;
would be ideal if the primary constructor had no code

2024-09-09 11:22 UTC, eemhu commented on src/main/java/com/teragrep/pth_06/planner/BloomFilterTempTable.java
> +            throw new UncheckedIOException(e);
perhaps it would be worth it to add some extra context to this exception in addition to the original exception to help debugging in the future.

2024-09-09 12:18 UTC, eemhu commented on src/test/java/com/teragrep/pth_06/planner/BloomFilterTempTableTest.java
> +        Assertions.assertThrows(RuntimeException.class, tempTable::generateCondition);
check that RuntimeException.getMessage() is of expected value?

2024-09-09 12:30 UTC, eemhu commented on src/test/java/com/teragrep/pth_06/walker/ConditionWalkerTest.java
> +    void singleTalbePatternMatchTest() {
typo

2024-09-09 13:09 UTC, kortemik requested changes
please rebase this on the latest main branch, it has commits that do not belong here. i.e. license changes

2024-09-12 07:37 UTC, elliVM commented
Moving to another branch

2024-09-12 07:37 UTC, closed without merging